### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Wisesaaa** [dante4rt/sonic-odyssey-bot#1]
Failed to send SOL to 7eVi6A11L*******1gaakJ2jmnndtaHybp5FWXUSbsg: SendTransactionError: Simulation failed.
Message: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit..
Logs:
[].
Catch the `SendTransactionError` and call `getLogs()` on it for full details.
    at Connection.sendEncodedTransaction (C:\Users\*****\sonic-odyssey-bot\node_modules\@solana\web3.js\lib\index.cjs.js:8114:13)

**Comment by dante4rt** [comment]
> Failed to send SOL to 7eVi6A11L*****1gaakJ2jmnndtaHybp5FWXUSbsg: SendTransactionError: Simulation failed. Message: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.. Logs: []. Catch the `SendTransactionError` and call `getLogs()` on it for full details. at Connection.sendEncodedTransaction (C:\Users***\sonic-odyssey-bot\node_modules@solana\web3.js\lib\index.cjs.js:8114:13)

I assume the error occurred because:
1. You don't have enough funds to complete the transaction.
2. There is a connection problem with the RPC.

Could you please check these?
