### ISSUE TITLE
Bot Crashed

### ISSUE THREAD

**Issue by Symonpeetta** [dante4rt/sonic-odyssey-bot#10]
![Screenshot_20240720-123853](https://github.com/user-attachments/assets/d201d2cb-66a4-4a24-a631-5990a220801d)

**Comment by dante4rt** [comment]
> ![Screenshot_20240720-123853](https://private-user-images.githubusercontent.com/65063958/350689136-d201d2cb-66a4-4a24-a631-5990a220801d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMTU1NjUsIm5iZiI6MTcyMjAxNTI2NSwicGF0aCI6Ii82NTA2Mzk1OC8zNTA2ODkxMzYtZDIwMWQyY2ItNjZhNC00YTI0LWE2MzEtNTk5MGEyMjA4MDFkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDE3MzQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0ZDU2ZTAxZDFjNDU1ZTRlNjRmZmU5ODZiNzdlYzk5NTU1NTQzY2E1MTQxNjY2NTU4MTk1NGE4ZTQxODYzNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3hznYN_BW-NhsVhWhN1_fu5R4PW-SsyN6M1XwD7v50A)

RPC problems, you can read it from that log.
