### ISSUE TITLE
add line of code to select between which private key or seed phrase to use.

### ISSUE THREAD

**Issue by LegendaryTunzeverywhere** [dante4rt/sonic-odyssey-bot#11]
The bot is designed to finish with one wallet and move to the next which is fine, but to be able to organize the privatekey the way they would to the seed phrase. Adding option to which private key to use will be great.

**Comment by dante4rt** [comment]
> The bot is designed to finish with one wallet and move to the next which is fine, but to be able to organize the privatekey the way they would to the seed phrase. Adding option to which private key to use will be great.

Thanks for the feedback, I will try to improve my code.
