### ISSUE TITLE
Eror for runinng npm start 

### ISSUE THREAD

**Issue by GilangPortofolio** [dante4rt/sonic-odyssey-bot#2]
npm start[4620]: c:\ws\src\node_file.cc:2183: Assertion `(argc) == (5)' failed.
 1: 00007FF6B09C433F node::SetCppgcReference+15695
 2: 00007FF6B093EC26 EVP_MD_meth_get_input_blocksize+78566
 3: 00007FF6B093F022 EVP_MD_meth_get_input_blocksize+79586
 4: 00007FF6B09316AD EVP_MD_meth_get_input_blocksize+23917
 5: 00007FF6B1360BBE v8::SharedValueConveyor::SharedValueConveyor+416270
 6: 00007FF6B13607BA v8::SharedValueConveyor::SharedValueConveyor+415242
 7: 00007FF6B1360A7F v8::SharedValueConveyor::SharedValueConveyor+415951
 8: 00007FF6B13608F0 v8::SharedValueConveyor::SharedValueConveyor+415552
 9: 00007FF6B145B28E v8::PropertyDescriptor::writable+674286
10: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256
11: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256
12: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256
13: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256
14: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256
15: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256
16: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256
17: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256
18: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256
19: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256
20: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256
21: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256
22: 00007FF6B13CACF0 v8::PropertyDescriptor::writable+83024
23: 00007FF6B13CA8EB v8::PropertyDescriptor::writable+81995
24: 00007FF6B12759B8 v8::StackTrace::GetFrameCount+3944
25: 00007FF6B12752B3 v8::StackTrace::GetFrameCount+2147
26: 00007FF6B138995B v8::Function::Call+571
27: 00007FF6B095DE0A node::OnFatalError+119786
28: 00007FF6B08BAAB6 node::TriggerNodeReport+22998
29: 00007FF6B097F027 node::Start+1095
30: 00007FF6B09F6D29 node::LoadEnvironment+89
31: 00007FF6B08ED8F7 X509_STORE_get_cleanup+151527
32: 00007FF6B097FB75 node::Start+3989
33: 00007FF6B097EC10 node::Start+48
34: 00007FF6B075EA3C AES_cbc_encrypt+151660
35: 00007FF6B1B9323C inflateValidate+17308
36: 00007FFCDB387344 BaseThreadInitThunk+20

**Comment by dante4rt** [comment]
> npm start[4620]: c:\ws\src\node_file.cc:2183: Assertion `(argc) == (5)' failed. 1: 00007FF6B09C433F node::SetCppgcReference+15695 2: 00007FF6B093EC26 EVP_MD_meth_get_input_blocksize+78566 3: 00007FF6B093F022 EVP_MD_meth_get_input_blocksize+79586 4: 00007FF6B09316AD EVP_MD_meth_get_input_blocksize+23917 5: 00007FF6B1360BBE v8::SharedValueConveyor::SharedValueConveyor+416270 6: 00007FF6B13607BA v8::SharedValueConveyor::SharedValueConveyor+415242 7: 00007FF6B1360A7F v8::SharedValueConveyor::SharedValueConveyor+415951 8: 00007FF6B13608F0 v8::SharedValueConveyor::SharedValueConveyor+415552 9: 00007FF6B145B28E v8::PropertyDescriptor::writable+674286 10: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256 11: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256 12: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256 13: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256 14: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256 15: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256 16: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256 17: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256 18: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256 19: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256 20: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256 21: 00007FF6B13CC930 v8::PropertyDescriptor::writable+90256 22: 00007FF6B13CACF0 v8::PropertyDescriptor::writable+83024 23: 00007FF6B13CA8EB v8::PropertyDescriptor::writable+81995 24: 00007FF6B12759B8 v8::StackTrace::GetFrameCount+3944 25: 00007FF6B12752B3 v8::StackTrace::GetFrameCount+2147 26: 00007FF6B138995B v8::Function::Call+571 27: 00007FF6B095DE0A node::OnFatalError+119786 28: 00007FF6B08BAAB6 node::TriggerNodeReport+22998 29: 00007FF6B097F027 node::Start+1095 30: 00007FF6B09F6D29 node::LoadEnvironment+89 31: 00007FF6B08ED8F7 X509_STORE_get_cleanup+151527 32: 00007FF6B097FB75 node::Start+3989 33: 00007FF6B097EC10 node::Start+48 34: 00007FF6B075EA3C AES_cbc_encrypt+151660 35: 00007FF6B1B9323C inflateValidate+17308 36: 00007FFCDB387344 BaseThreadInitThunk+20

Its your NodeJS version problem, not comes from this code.

Try this:
```
rm -rf node_modules package-lock.json
npm install
```

If the issues still persist, re-check your NodeJS version nor re-install it with the compatible one.

**Comment by GilangPortofolio** [comment]
I have followed your instructions to reinstall, but it still has a similar error. I'm curious which version of NodeJs is compatible with this script. because currently on my computer my node v20.9.0 is installed

**Comment by dante4rt** [comment]
> I have followed your instructions to reinstall, but it still has a similar error. I'm curious which version of NodeJs is compatible with this script. because currently on my computer my node v20.9.0 is installed

Hmmm.. interesting, since it works on other users. Anyway, I use `v20.7.0`.

**Comment by GilangPortofolio** [comment]
ok, I'll try to downgrade it later, but I can already run it on gitlab. If I have downgraded it later, can I give feedback again?

**Comment by dante4rt** [comment]
> ok, I'll try to downgrade it later, but I can already run it on gitlab. If I have downgraded it later, can I give feedback again?

Sure, let me know! :)
