### ISSUE TITLE
Bot error

### ISSUE THREAD

**Issue by presifour** [dante4rt/sonic-odyssey-bot#7]
Your bot error

![Uploading Screenshot_20240704-104001.jpg…]()

**Comment by hokicuanxz** [comment]
can you help me
![Screenshot (65)](https://github.com/user-attachments/assets/9c6a75b7-3e4c-4520-b85d-cb73836b82c8)

**Comment by mesamirh** [comment]
Those facing this problem just upgrade your node.js to minimum v15 which supports the logical OR assignment operator (||=)

**Comment by dante4rt** [comment]
> Those facing this problem just upgrade your node.js to minimum v15 which supports the logical OR assignment operator (||=)

Thanks for the heads up! Yes, correct.
